url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

collections:
  projects:
    output: true
    order:
      - icarus.html
      - archer.html
      - raytracer.html
      - ansify.html
  writeups:
    output: true
    order:
      - defcamp-2020-qr-mania.html
      - unbreakable-romania-online-1-russiandoll.html
      - pwnable-xyz-sub.html
      - pwnable-xyz-welcome.html
  scripts:
    output: true